services:
  config-server:
    build: ../config-server
    mem_limit: 512m
    ports:
      - "8888:8888"
    environment:
      GITHUB_URL: ${GITHUB_URL}
      GITHUB_USERNAME: ${GITHUB_USERNAME}
      GITHUB_TOCKEN: ${GITHUB_TOCKEN}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s     
      timeout: 10s    
      retries: 5        
      start_period: 60s
    networks:
      - electrodostore-network


  eureka-server:
    build: ../eureka-server
    mem_limit: 512m
    ports:
      - "8761:8761"
    environment:
      CONFIG_SERVER_URL: ${CONFIG_SERVER_URL}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s     
      timeout: 10s    
      retries: 5        
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy    
    networks:
      - electrodostore-network


networks:
  electrodostore-network:
    driver: bridge


  

